import {
  RepeatVsAddExercise,
  WhatHappensNextPrompt,
  ExampleEnginePrompt,
  SentenceForgePrompt,
} from "@/types";

export const SEED_REPEAT_VS_ADD: RepeatVsAddExercise[] = [
  // Obvious & Paraphrased Repetitions
  {
    id: "rva-1",
    topic: "Regular exercise improves physical health.",
    domain: "health",
    sentence1: "Regular exercise significantly improves physical wellbeing.",
    sentence2: "Working out regularly helps people maintain good fitness and bodily health.",
    correctAnswer: "REPEAT",
    explanation: "Sentence 2 only rephrases 'exercise improves health' without offering a new reason, example, or consequence.",
    difficulty: 1,
  },
  {
    id: "rva-2",
    topic: "Public parks improve city life.",
    domain: "society",
    sentence1: "Public parks provide a calming natural retreat for busy city dwellers.",
    sentence2: "They also reduce urban heat by offering shaded canopies and absorbing less sunlight than concrete.",
    correctAnswer: "ADD",
    explanation: "Sentence 2 introduces a completely new environmental benefit (reducing urban heat), advancing the reasoning.",
    difficulty: 1,
  },
  {
    id: "rva-3",
    topic: "Single-use plastics should be banned.",
    domain: "environment",
    sentence1: "Single-use plastics cause tremendous harm to marine wildlife.",
    sentence2: "Disposable plastic items frequently injure and poison sea creatures in the ocean.",
    correctAnswer: "REPEAT",
    explanation: "Both sentences state the exact same point: plastics harm sea life. Sentence 2 merely uses synonyms.",
    difficulty: 1,
  },
  {
    id: "rva-4",
    topic: "Single-use plastics should be banned.",
    domain: "environment",
    sentence1: "Single-use plastics cause tremendous harm to marine wildlife.",
    sentence2: "Furthermore, plastic manufacturing consumes non-renewable crude oil that accelerates climate change.",
    correctAnswer: "ADD",
    explanation: "Sentence 2 moves from ocean harm to resource depletion during manufacturing—a brand new angle.",
    difficulty: 2,
  },
  {
    id: "rva-5",
    topic: "Public libraries are still essential.",
    domain: "society",
    sentence1: "Libraries are important because they offer free books to the public.",
    sentence2: "Without libraries, many low-income families would not be able to afford books.",
    correctAnswer: "ADD",
    explanation: "Sentence 2 explains WHY free books matter (equity for low-income families), advancing the cause-and-effect.",
    difficulty: 2,
  },
  {
    id: "rva-6",
    topic: "Public libraries are still essential.",
    domain: "society",
    sentence1: "Libraries provide quiet spaces where students can study without distraction.",
    sentence2: "They offer peaceful rooms that allow children to concentrate on homework undisturbed.",
    correctAnswer: "REPEAT",
    explanation: "Sentence 2 is an echo of sentence 1. It repeats the idea of a quiet study space using different words.",
    difficulty: 2,
  },
  {
    id: "rva-7",
    topic: "Cars should be restricted in city centres.",
    domain: "cities" as any,
    sentence1: "Limiting vehicle access makes inner-city streets substantially safer for pedestrians.",
    sentence2: "When streets have fewer motor vehicles, walking people face a much lower risk of collisions.",
    correctAnswer: "REPEAT",
    explanation: "Saying pedestrians are safer and walking people face less collisions is repeating the same point.",
    difficulty: 2,
  },
  {
    id: "rva-8",
    topic: "Cars should be restricted in city centres.",
    domain: "environment",
    sentence1: "Limiting vehicle access makes inner-city streets substantially safer for pedestrians.",
    sentence2: "Consequently, families and elderly residents are more willing to visit local shops on foot.",
    correctAnswer: "ADD",
    explanation: "Sentence 2 identifies a commercial and community consequence resulting from pedestrian safety.",
    difficulty: 3,
  },
  {
    id: "rva-9",
    topic: "Repairing broken items is better than buying new ones.",
    domain: "money_and_resources",
    sentence1: "Fixing appliances reduces the total volume of trash dumped into municipal landfills.",
    sentence2: "It also encourages individuals to develop practical mechanical problem-solving skills.",
    correctAnswer: "ADD",
    explanation: "Sentence 1 focuses on waste reduction; sentence 2 introduces personal learning and skill-building.",
    difficulty: 2,
  },
  {
    id: "rva-10",
    topic: "Failure is a necessary step towards success.",
    domain: "values",
    sentence1: "Experiencing setbacks reveals specific errors that need correction.",
    sentence2: "Making mistakes highlights the precise areas where a person's technique fell short.",
    correctAnswer: "REPEAT",
    explanation: "Both sentences explain that mistakes show what went wrong. Sentence 2 does not explain what happens next.",
    difficulty: 3,
  },
  {
    id: "rva-11",
    topic: "Failure is a necessary step towards success.",
    domain: "values",
    sentence1: "Experiencing setbacks reveals specific errors that need correction.",
    sentence2: "More importantly, recovering from failure builds emotional resilience when facing future difficulties.",
    correctAnswer: "ADD",
    explanation: "Sentence 2 shifts from diagnostic technical correction to psychological resilience.",
    difficulty: 3,
  },
  {
    id: "rva-12",
    topic: "Museums should be free.",
    domain: "society",
    sentence1: "Free admission allows people of all economic backgrounds to access historical knowledge.",
    sentence2: "Anyone can visit and learn regardless of how much money they earn.",
    correctAnswer: "REPEAT",
    explanation: "Paraphrased repetition: 'all economic backgrounds' and 'regardless of how much money' are identical ideas.",
    difficulty: 2,
  },
];

export const SEED_WHAT_HAPPENS_NEXT: WhatHappensNextPrompt[] = [
  {
    id: "whn-1",
    topic: "Cities should plant more trees along every street.",
    domain: "environment",
    point: "Trees provide natural shade along city streets.",
    whyPrompt: "What happens because streets have more natural shade?",
    sampleNext: "Pedestrian walkways and buildings absorb less heat during hot summer days.",
    sampleMatter: "People can walk and commute comfortably without risking heat exhaustion or relying on high-cost air conditioning.",
  },
  {
    id: "whn-2",
    topic: "Public transport should be cheaper or free.",
    domain: "society",
    point: "Cheaper ticket fares encourage commuters to leave their cars at home.",
    whyPrompt: "What happens when thousands of commuters switch to public transport?",
    sampleNext: "Daily traffic congestion on major arterial highways drops significantly.",
    sampleMatter: "Emergency vehicles can move faster, goods are delivered on time, and harmful vehicle emissions are cut down.",
  },
  {
    id: "whn-3",
    topic: "Schools should teach practical financial skills.",
    domain: "money_and_resources",
    point: "Students learn the basics of budgeting and compounding interest.",
    whyPrompt: "What happens when young people understand how compounding interest and debts work?",
    sampleNext: "They avoid accumulating high-interest credit card debts when entering adulthood.",
    sampleMatter: "Young adults can achieve financial independence earlier and make responsible life decisions without crippling debt.",
  },
  {
    id: "whn-4",
    topic: "Repairing broken items is better than buying new ones.",
    domain: "money_and_resources",
    point: "Repairing things extends the working life of appliances and electronics.",
    whyPrompt: "What happens when families keep using existing electronics for longer?",
    sampleNext: "Fewer manufactured goods are bought each year, reducing manufacturing demand.",
    sampleMatter: "Massive amounts of scarce raw minerals are preserved, and landfills are not filled with toxic electronic waste.",
  },
  {
    id: "whn-5",
    topic: "Too many choices can make life worse.",
    domain: "rules_and_freedom",
    point: "When faced with dozens of similar options, people overthink their decision.",
    whyPrompt: "What happens when people spend too much energy evaluating minor differences?",
    sampleNext: "They experience decision fatigue and constant anxiety that they picked the wrong option.",
    sampleMatter: "Instead of enjoying their choice, they feel lingering regret, diminishing their overall satisfaction and peace of mind.",
  },
];

export const SEED_EXAMPLE_PROMPTS: ExampleEnginePrompt[] = [
  {
    id: "ex-1",
    topic: "Repairing products instead of replacing them saves valuable resources.",
    domain: "money_and_resources",
    argument: "Replacing a single worn component can restore a complex machine to working order.",
    weakExample: "For example, repairing things is good for saving materials.",
    strongExampleTip: "Name a specific object (e.g. replacing a bicycle chain or phone battery) and contrast fixing one part vs throwing the entire device away.",
  },
  {
    id: "ex-2",
    topic: "Public libraries are still vital in the digital age.",
    domain: "society",
    argument: "Libraries bridge the digital divide by providing equal access to costly modern equipment.",
    weakExample: "For example, libraries have lots of technology for people.",
    strongExampleTip: "Mention a specific tool (like high-speed Wi-Fi, 3D printers, or subscription research databases) that a student or job seeker could not afford at home.",
  },
  {
    id: "ex-3",
    topic: "Convenience foods do more harm than good in modern society.",
    domain: "health",
    argument: "Pre-packaged fast foods sacrifice essential nutrients for long shelf life and quick preparation.",
    weakExample: "For example, fast food is not healthy for people.",
    strongExampleTip: "Give a concrete example: swapping a fresh home-cooked vegetable meal for ultra-processed frozen meals loaded with sodium, preservatives, and saturated fats.",
  },
  {
    id: "ex-4",
    topic: "Failure is a necessary step towards genuine success.",
    domain: "values",
    argument: "Initial mistakes expose hidden flaws that would otherwise remain unnoticed.",
    weakExample: "For example, people fail before they win.",
    strongExampleTip: "Describe an inventor or scientist (like Edison testing lightbulb filaments or an engineer whose first bridge model collapsed) refining their design based on the exact flaw.",
  },
];

export const SEED_SENTENCE_FORGE: SentenceForgePrompt[] = [
  {
    id: "sf-1",
    simpleSentences: [
      "Mia was nervous about the scholarship exam.",
      "Mia walked onto the stage.",
      "The examination hall was completely silent.",
    ],
    suggestedConjunctions: ["Although", "as", "despite"],
    modelSentence: "Although Mia was nervous about the scholarship exam, she stepped onto the stage as the hall fell completely silent.",
  },
  {
    id: "sf-2",
    simpleSentences: [
      "Cities plant leafy trees along footpaths.",
      "Trees absorb solar heat.",
      "Pedestrians can walk comfortably on scorching summer afternoons.",
    ],
    suggestedConjunctions: ["Because", "so that", "which"],
    modelSentence: "Because leafy trees absorb solar heat, cities that plant them along footpaths allow pedestrians to walk comfortably even on scorching summer afternoons.",
  },
  {
    id: "sf-3",
    simpleSentences: [
      "Modern smartphones offer instant entertainment.",
      "Constantly checking notifications shortens attention spans.",
      "Many educators recommend daily screen-free periods.",
    ],
    suggestedConjunctions: ["While", "therefore", "since"],
    modelSentence: "While modern smartphones offer instant entertainment, constantly checking notifications shortens attention spans; therefore, many educators recommend daily screen-free periods.",
  },
  {
    id: "sf-4",
    simpleSentences: [
      "Repairing a cracked phone screen takes effort.",
      "Repairing the screen costs far less than buying a brand-new handset.",
      "It prevents toxic electronic waste from entering local landfills.",
    ],
    suggestedConjunctions: ["Even though", "not only... but also", "because"],
    modelSentence: "Even though repairing a cracked phone screen takes effort, it not only costs far less than buying a new handset but also prevents toxic electronic waste from entering landfills.",
  },
];
