import { ClearAndCompletePrompt } from "@/types";

export const SEED_CLEAR_AND_COMPLETE: ClearAndCompletePrompt[] = [
  /* ============================================================
     TYPE A: BUILD THE BRIDGE (Point A -> Missing Bridge B -> Conclusion C)
     ============================================================ */
  {
    id: "cnc-btb-1",
    taskType: "build_the_bridge",
    title: "Playground Trees & Summer Comfort",
    domain: "environment",
    difficulty: "easy",
    timeLimitSeconds: 45,
    context: {
      pointA: "A school plants large shade trees around its outdoor playground.",
      conclusionC: "The playground becomes significantly more comfortable for students during hot summer days.",
    },
    targetMechanismTip: "Explain how large trees physically change the playground environment (e.g. canopy blocking direct sun/heat). Stop once comfort is explained.",
    modelAnswer: "As the trees grow, their leafy branches block direct sunlight and cast shade across the playground equipment.",
  },
  {
    id: "cnc-btb-2",
    taskType: "build_the_bridge",
    title: "Dining Table Repair vs Replacement",
    domain: "money_and_resources",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      pointA: "A family repairs the single broken leg of its sturdy dining table for $30.",
      conclusionC: "Repairing the table is much better value than replacing it.",
    },
    targetMechanismTip: "Compare the small repair cost with the much higher cost of buying an entire new table. Stop once value comparison is proved.",
    modelAnswer: "Buying a brand new dining table would cost hundreds of dollars, so spending $30 to fix the only damaged part avoids a large replacement expense.",
  },
  {
    id: "cnc-btb-3",
    taskType: "build_the_bridge",
    title: "Bicycle Commute Petrol Savings",
    domain: "transport",
    difficulty: "easy",
    timeLimitSeconds: 45,
    context: {
      pointA: "A commuter chooses to ride a bicycle instead of driving a car for short local trips.",
      conclusionC: "The commuter saves money on weekly travel expenses.",
    },
    targetMechanismTip: "Identify the exact expense cars require that bicycles do not (e.g. petrol/fuel). Stop once the saving is clear.",
    modelAnswer: "Bicycles are powered by pedalling rather than petrol, so the rider does not have to pay for fuel on those trips.",
  },
  {
    id: "cnc-btb-4",
    taskType: "build_the_bridge",
    title: "Wildlife Corridors & Road Safety",
    domain: "animals",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      pointA: "A regional council builds an overhead vegetated bridge connecting two disconnected forest reserves across a highway.",
      conclusionC: "Vehicle collisions involving native wildlife decrease substantially along that stretch of road.",
    },
    targetMechanismTip: "Explain how the overhead bridge changes animal movement relative to traffic. Stop once collision reduction is established.",
    modelAnswer: "Animals use the vegetated overpass to cross safely above the road instead of wandering into high-speed highway traffic.",
  },
  {
    id: "cnc-btb-5",
    taskType: "build_the_bridge",
    title: "Public Library Digital Access",
    domain: "community",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      pointA: "The community library installs high-speed internet terminals with free access for all residents.",
      conclusionC: "Local job seekers from low-income households find employment opportunities more readily.",
    },
    targetMechanismTip: "Connect internet terminals to the practical steps of finding and applying for jobs.",
    modelAnswer: "The terminals allow residents who cannot afford home internet to search online job listings, submit resumes, and check employer emails.",
  },
  {
    id: "cnc-btb-6",
    taskType: "build_the_bridge",
    title: "Drip Irrigation in Agriculture",
    domain: "science",
    difficulty: "hard",
    timeLimitSeconds: 75,
    context: {
      pointA: "A farming community switches from open overhead sprinklers to underground drip irrigation tubes.",
      conclusionC: "The farms conserve substantial amounts of regional water without reducing crop yields.",
    },
    targetMechanismTip: "Explain why drip irrigation prevents water loss compared to sprinklers (e.g. delivers directly to roots, avoids evaporation).",
    modelAnswer: "Drip lines release water directly at the plant roots beneath the soil, preventing water from evaporating into the air or blowing away in the wind.",
  },
  {
    id: "cnc-btb-7",
    taskType: "build_the_bridge",
    title: "School Uniform Standardisation",
    domain: "fairness",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      pointA: "A primary school requires all students to wear identical, affordable school uniforms.",
      conclusionC: "Social friction and bullying regarding household wealth decline among peers.",
    },
    targetMechanismTip: "Explain how identical uniforms conceal differences in family wealth or designer clothing.",
    modelAnswer: "When everyone wears the same uniform, differences in expensive designer clothing or family financial background are no longer visible in class.",
  },
  {
    id: "cnc-btb-8",
    taskType: "build_the_bridge",
    title: "LED Streetlights & Municipal Budgets",
    domain: "money_and_resources",
    difficulty: "easy",
    timeLimitSeconds: 45,
    context: {
      pointA: "A town upgrades older sodium vapour streetlights to modern LED bulbs.",
      conclusionC: "The town council reduces its ongoing electricity expenditure each month.",
    },
    targetMechanismTip: "Identify why LEDs reduce expenditure (e.g. consume far less electrical power for equal light).",
    modelAnswer: "LED bulbs produce equal illumination while drawing significantly less electrical power than older lighting.",
  },

  /* ============================================================
     TYPE B: SAY IT CLEARLY (Filter Facts -> Connect Crucial Mechanism -> Stop)
     ============================================================ */
  {
    id: "cnc-sic-1",
    taskType: "say_it_clearly",
    title: "Maya's School Journey",
    domain: "transport",
    difficulty: "easy",
    timeLimitSeconds: 45,
    context: {
      facts: [
        "Maya lives 800 metres from her primary school.",
        "Her parents normally drive her in the morning.",
        "The drive takes ten minutes because of traffic congestion.",
        "Walking the same distance takes twelve minutes.",
        "She wants to incorporate more physical exercise into her daily routine.",
      ],
      question: "Explain one clear advantage of Maya walking to school instead of being driven.",
    },
    targetMechanismTip: "Use the relevant exercise benefit and time comparison (adds only 2 minutes). Do not wander into grades or wellbeing chains.",
    modelAnswer: "Walking to school would provide Maya with daily physical exercise while adding only two minutes to her travel time.",
  },
  {
    id: "cnc-sic-2",
    taskType: "say_it_clearly",
    title: "Replacing Lost Library Books",
    domain: "money_and_resources",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      facts: [
        "A standard school library book costs $25 to purchase.",
        "When a student loses a book, the school library must buy a replacement copy.",
        "Approximately 20 students lose library books across the school year.",
        "The school library operates on a fixed annual purchasing budget.",
      ],
      question: "Explain why students should look after their borrowed library books carefully.",
    },
    targetMechanismTip: "Connect lost books to diverted funds: replacing books forces the school to spend budget money that could have bought new resources.",
    modelAnswer: "When students lose library books, the school must spend budget money replacing identical copies instead of purchasing new learning resources.",
  },
  {
    id: "cnc-sic-3",
    taskType: "say_it_clearly",
    title: "Rechargeable Batteries in Classrooms",
    domain: "environment",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      facts: [
        "Disposable alkaline batteries cost $1 each and are thrown away after single use.",
        "Rechargeable battery sets cost $12 each and can be recharged up to 500 times.",
        "The science lab uses dozens of sensors throughout the school term.",
        "Discarded disposable batteries often end up in general landfill waste.",
      ],
      question: "Explain why the science lab should invest in rechargeable battery sets.",
    },
    targetMechanismTip: "Demonstrate the value or waste reduction directly using the facts, without speculative emotional chains.",
    modelAnswer: "Because rechargeable batteries can be reused hundreds of times, they eliminate the need to repeatedly buy and discard disposable batteries for lab sensors.",
  },
  {
    id: "cnc-sic-4",
    taskType: "say_it_clearly",
    title: "Pedestrian Crossing Outside School",
    domain: "community",
    difficulty: "easy",
    timeLimitSeconds: 45,
    context: {
      facts: [
        "Around 350 students cross Main Street each morning before bell time.",
        "Vehicles frequently travel along Main Street at 50 km/h.",
        "Currently, there is no signalised crossing or zebra crossing within 200 metres of the school gate.",
        "A signalised pedestrian crossing forces drivers to come to a complete stop upon button activation.",
      ],
      question: "Explain why installing a pedestrian crossing directly outside the school improves student safety.",
    },
    targetMechanismTip: "Explain the safety mechanism: gives children a protected interval by stopping vehicles before children step onto the road.",
    modelAnswer: "A signalised crossing stops moving vehicles, giving hundreds of arriving students a protected window to cross the street without dodging traffic.",
  },
  {
    id: "cnc-sic-5",
    taskType: "say_it_clearly",
    title: "Food Waste Compost in Community Gardens",
    domain: "conservation",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      facts: [
        "Local households throw out roughly 2 tonnes of vegetable scraps each month.",
        "Vegetable scraps in enclosed landfills decompose without oxygen and release methane gas.",
        "Composting aerates organic matter, converting scraps into rich, chemical-free garden fertiliser.",
        "The community garden currently buys commercial bagged fertiliser.",
      ],
      question: "Explain one practical environmental benefit of households composting vegetable scraps.",
    },
    targetMechanismTip: "Connect composting to preventing landfill methane or creating natural fertiliser from existing waste.",
    modelAnswer: "Composting organic scraps converts food waste into natural garden fertiliser instead of letting it produce methane gas in landfills.",
  },
  {
    id: "cnc-sic-6",
    taskType: "say_it_clearly",
    title: "Public Water Refill Stations",
    domain: "everyday_objects",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      facts: [
        "Single-use plastic water bottles take hundreds of years to break down in waterways.",
        "Bottled water costs around $3.50 per bottle at parks.",
        "Installing chilled municipal refill taps allows park visitors to refill personal flasks with tap water for free.",
        "Over 1,000 visitors visit the regional sports park each Saturday.",
      ],
      question: "Explain why installing public refill taps reduces single-use plastic waste in the park.",
    },
    targetMechanismTip: "Explain why visitors will choose refills over buying new plastic bottles (free and easy access).",
    modelAnswer: "Free public refill taps encourage visitors to carry reusable bottles, removing the need to buy disposable plastic bottles at the park.",
  },

  /* ============================================================
     TYPE C: CUT THE WASTE (Remove Unnecessary Causal Runaway / Preserve Full Logic)
     ============================================================ */
  {
    id: "cnc-ctw-1",
    taskType: "cut_the_waste",
    title: "Bicycle Petrol Savings Without The Drama",
    domain: "transport",
    difficulty: "easy",
    timeLimitSeconds: 45,
    context: {
      originalText: "Riding a bicycle to a nearby shop can save money because a bicycle does not need petrol. Petrol costs money, and spending money can make families stressed. Stress can make people unhappy and being unhappy can affect people's wellbeing.",
      goalProposition: "Explain why riding a bicycle to nearby shops saves money.",
    },
    targetMechanismTip: "Keep the fuel-saving mechanism. Cut the entire stress, unhappiness, and wellbeing runaway train.",
    modelAnswer: "Riding a bicycle to a nearby shop saves money because pedal bicycles do not require expensive petrol.",
  },
  {
    id: "cnc-ctw-2",
    taskType: "cut_the_waste",
    title: "Playground Bins & Litter Control",
    domain: "community",
    difficulty: "easy",
    timeLimitSeconds: 45,
    context: {
      originalText: "If students put rubbish in bins, less rubbish will be left on the playground. A cleaner playground looks nicer, which makes students happier. Happy students may enjoy school more, which might make them work harder and eventually achieve better results.",
      goalProposition: "Explain why placing rubbish into bins helps keep the school playground clean.",
    },
    targetMechanismTip: "Stop once cleanliness is established. Do not follow the rabbit hole into happiness, working harder, or academic exam results.",
    modelAnswer: "When students put their rubbish into bins, less litter remains scattered across the grounds, keeping the playground clean.",
  },
  {
    id: "cnc-ctw-3",
    taskType: "cut_the_waste",
    title: "Table Leg Repair Cost Comparison",
    domain: "money_and_resources",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      originalText: "Repairing a broken table leg costs only thirty dollars, whereas buying a new dining table costs several hundred dollars. This keeps more money in the family's bank account, which prevents financial arguments between parents, which ensures the household is peaceful and helps the children study calmly for their exams.",
      goalProposition: "Explain why repairing a table leg is more economical than replacing the entire table.",
    },
    targetMechanismTip: "Keep the cost comparison ($30 vs hundreds of dollars). Cut all the speculative domestic peace and exam study consequences.",
    modelAnswer: "Repairing a broken table leg for thirty dollars avoids having to spend several hundred dollars purchasing an entirely new table.",
  },
  {
    id: "cnc-ctw-4",
    taskType: "cut_the_waste",
    title: "Protective Shading in School Grounds",
    domain: "environment",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      originalText: "Installing shade sails over outdoor benches blocks intense ultraviolet rays, which shields children's skin from sunburn during lunch breaks. Avoiding sunburn keeps children comfortable, so they do not feel irritable, which means teachers spend less time settling disputes, allowing the school to run much more harmoniously.",
      goalProposition: "Explain why installing shade sails protects students from sun harm.",
    },
    targetMechanismTip: "Keep the UV blocking and sunburn prevention mechanism. Cut the irritable children, teacher disputes, and school harmony claims.",
    modelAnswer: "Installing shade sails over outdoor benches blocks intense ultraviolet radiation, protecting children from harmful sunburn during lunch breaks.",
  },
  {
    id: "cnc-ctw-5",
    taskType: "cut_the_waste",
    title: "Insulating Old Houses",
    domain: "science",
    difficulty: "hard",
    timeLimitSeconds: 75,
    context: {
      originalText: "Adding ceiling insulation traps warm air inside a home during winter so electric heaters do not need to run continuously. Using heaters less reduces quarterly electricity bills, which frees up cash for groceries, which lowers parental worry, which creates a positive home atmosphere where everyone feels supported.",
      goalProposition: "Explain how ceiling insulation reduces home heating costs during winter.",
    },
    targetMechanismTip: "Keep the thermal retention mechanism and reduced heating run time. Cut grocery cash, parental worry, and supportive atmosphere.",
    modelAnswer: "Ceiling insulation traps warm air indoors, reducing the amount of time electric heaters must run and lowering electricity bills.",
  },
  {
    id: "cnc-ctw-6",
    taskType: "cut_the_waste",
    title: "Regular Dog Walking & Health",
    domain: "animals",
    difficulty: "easy",
    timeLimitSeconds: 45,
    context: {
      originalText: "Taking a dog on daily walks provides regular aerobic exercise that strengthens its heart and prevents excess weight gain. When dogs maintain a healthy weight they live longer, which means owners avoid the grief of pet illness, which prevents owners from missing work due to sadness, which protects the local economy.",
      goalProposition: "Explain how daily walks benefit a pet dog's physical health.",
    },
    targetMechanismTip: "Keep the dog's exercise and weight/heart benefit. Cut the owner grief, missing work, and local economy runaway.",
    modelAnswer: "Daily walks provide dogs with aerobic exercise that strengthens their cardiovascular health and prevents unhealthy weight gain.",
  },
  {
    id: "cnc-ctw-7",
    taskType: "cut_the_waste",
    title: "Backup Power Generators for Hospitals",
    domain: "technology",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      originalText: "Hospitals maintain backup diesel generators so that critical life-support machines and operating theatres continue running if the main electrical grid fails. If life-support machines keep running, patients do not suffer sudden respiratory failure. This protects lives, which prevents families from filing lawsuits against doctors, which prevents malpractice insurance rates from skyrocketing across the state.",
      goalProposition: "Explain why hospitals require backup power generators.",
    },
    targetMechanismTip: "Keep the emergency power continuity for life-support systems. Cut malpractice lawsuits and state insurance rates.",
    modelAnswer: "Hospitals require backup generators to ensure critical life-support machines and operating rooms continue operating during power outages.",
  },
  {
    id: "cnc-ctw-8",
    taskType: "cut_the_waste",
    title: "Quiet Reading Corners in Classrooms",
    domain: "rules_and_freedom",
    difficulty: "standard",
    timeLimitSeconds: 60,
    context: {
      originalText: "Creating a dedicated quiet corner with cushions gives children a calm space away from loud classroom noise so they can read without distractions. Concentrating on books helps them understand stories better, which makes them love literature, which inspires them to become authors who write bestsellers and influence global culture.",
      goalProposition: "Explain how a quiet corner helps students read effectively in class.",
    },
    targetMechanismTip: "Keep noise reduction and focused reading. Cut loving literature, becoming authors, and influencing global culture.",
    modelAnswer: "A quiet corner provides a calm area separated from classroom noise, allowing students to concentrate on their reading without distraction.",
  },
];
